# Generated by Django 3.2.5 on 2021-12-22 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_auto_20211222_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='comment',
            field=models.ManyToManyField(related_name='ads_comments', through='ads.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_ads', to='ads.ads'),
        ),
    ]
