# Generated by Django 3.2.5 on 2021-12-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='foods',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
